# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c15e091e75b4eb27df3dca55ffcaa4ad122498a8b1a920302d8449057e47813e4d58c7c59cf97fb89e8db961a2b1e5fa51dd6d69d83b1116e4c7444950f6def

test:
  secret_key_base: 2424d79fa1a1ae0d602d416a5fa6377aa69cdbdb233ff465306207619308b88530a7d278398ea97775ec86e53d820e7bea0d29c1e8d43cbc02cdeb7e296883cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
